- hosts: hadoop-master
  tasks:
    #- name: 安装
    #  copy: src=/opt/sqoop-1.4.7.bin__hadoop-2.6.0.tar.gz dest=/opt/

    #- name: 解压
    #  shell: tar -xzvf /opt/sqoop-1.4.7.bin__hadoop-2.6.0.tar.gz -C /opt/

    - name: 软链接
      file: src=/opt/sqoop-1.4.7.bin__hadoop-2.6.0 dest=/opt/sqoop state=link

    - name: MySQL JDBC
      file: src=/usr/share/java/mysql-connector-java.jar dest=/opt/sqoop/lib/mysql-connector-java.jar state=link

    - name: ENV
      copy:
        src: ./etc/profile.d/sqoop.sh
        dest: /etc/profile.d/

